### PR TITLE
Adding more links with infos about the datatracker

### PR DESCRIPTION
**Pull request by mirjak**
Maybe we need to confirm with Robert Sparks that we can have these links in an RFC or if we want to move to a more stable link (if possible).

### CODE REVIEW

**Comment by rjsparks** [comment]
How about having the RFC point to something like a general information page about workshops (which may have to be created) at the IAB website. That page can then always resolve to _something_ but the content can be dynamic.

In the long run, the information about the datatracker captured in the notes pointed to here can be put in a more permanent location/format, but that's not going to be in place in the timeframe that this report should be released by.

**Comment by rjsparks** [comment]
(Can't resist - sorry) Alternatively, we can accept that its OK to have some links in RFCs that are expected to become stale or go away over time, and mark them as such, but that would be a bigger policy change for the series.

**Comment by mirjak** [comment]
On the general issue: This is a weblink and not an explicit reference, so I'm actually not sure what the policy on stability is...

However, I think the easiest solution would be to move this content to a more permanent link, ideally somewhere "in" the datatracker as I assume this information is also useful to non-workshop participants. Or is there already a datatracker GitHub where we could add this information and then only link to the overall GitHub repo?

**Comment by rjsparks** [comment]
We're still working towards moving the datatracker into github - right now it's in trac/svn which would be a horrible place for this to land. Hopefully we'll get the move to github finished in a small number of weeks.

After thinking longer, I suggest just pointing to notes (as the PR does) and maybe adding a qualifier that says "at the time of the workshop ..."

**Pull request merged**
